### ISSUE TITLE
hassio addon: repository 'https://github.com/radinsky/hassio-addons/has1c/' not found

### ISSUE THREAD

**Issue by TomerFi** [radinsky/has1c#1]
Nice work, I've been looking for a way to connect to my s1c sensors with ha.
Thank you very much!

My issue is:
When trying to install the addon, nothing happens.
In the supervisor log it says: repository 'https://github.com/radinsky/hassio-addons/has1c/' not found.

I think the issue is in 'url' inside the 'repository.json' file.

**Comment by radinsky** [comment]
I left it a while ago, not sure it was working correctly. Will reupload my current version later
